services:
  flask-app:
    build:
      context: .
    volumes:
      - ./instance:/instance
    ports:
      - "80:80"
    restart: unless-stopped
    develop:
      watch:
        - path: ./src
          action: rebuild
        - path: ./main.py
          action: rebuild
        - path: ./requirements.txt
          action: rebuild
